defmodule Wekui.Repo.Migrations.CurationActs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:curation_acts, primary_key: false) do
      add :claim_id,
          references(:claims,
            column: :id,
            name: "curation_acts_claim_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :person_id,
          references(:persons,
            column: :id,
            name: "curation_acts_person_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :place_id,
          references(:places,
            column: :id,
            name: "curation_acts_place_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :actor_id,
          references(:actors,
            column: :id,
            name: "curation_acts_actor_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "curation_acts_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :after, :map
      add :before, :map
      add :reason, :text, null: false
      add :kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:curation_acts, ["actor_id"])

    create index(:curation_acts, ["event_id", "inserted_at"])
  end

  def down do
    drop_if_exists index(:curation_acts, ["event_id", "inserted_at"],
                     name: "curation_acts_event_id_inserted_at_index"
                   )

    drop_if_exists index(:curation_acts, ["actor_id"], name: "curation_acts_actor_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `curation_acts` table without the `curation_acts_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `curation_acts` table without the `curation_acts_actor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `curation_acts` table without the `curation_acts_place_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `curation_acts` table without the `curation_acts_person_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `curation_acts` table without the `curation_acts_claim_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:curation_acts)
  end
end
