defmodule Wekui.Repo.Migrations.CreateEvent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :timezone, :text, null: false
      add :goal, :text, null: false
      add :t0, :utc_datetime_usec, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:events, [:name], name: "events_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:events, [:name], name: "events_unique_name_index")

    drop table(:events)
  end
end
