defmodule Wekui.Repo.Migrations.AddThemeJudgments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:theme_none_judgments, primary_key: false) do
      add :superseded_by_id,
          references(:theme_none_judgments,
            column: :id,
            name: "theme_none_judgments_superseded_by_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :actor_id,
          references(:actors,
            column: :id,
            name: "theme_none_judgments_actor_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "theme_none_judgments_post_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "theme_none_judgments_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :superseded_at, :utc_datetime_usec
      add :judged_at, :utc_datetime_usec, null: false
      add :confidence, :float
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:theme_none_judgments, ["post_id"],
             name: "theme_none_judgments_current_post_index",
             unique: true,
             where: "superseded_at IS NULL"
           )

    create index(:theme_none_judgments, ["event_id"])

    create index(:theme_none_judgments, ["actor_id"])

    create table(:theme_judgments, primary_key: false) do
      add :superseded_by_id,
          references(:theme_judgments,
            column: :id,
            name: "theme_judgments_superseded_by_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :actor_id,
          references(:actors,
            column: :id,
            name: "theme_judgments_actor_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :theme_id,
          references(:themes,
            column: :id,
            name: "theme_judgments_theme_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "theme_judgments_post_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "theme_judgments_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :superseded_at, :utc_datetime_usec
      add :judged_at, :utc_datetime_usec, null: false
      add :confidence, :float
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:theme_judgments, ["post_id", "theme_id"],
             name: "theme_judgments_current_slot_index",
             unique: true,
             where: "superseded_at IS NULL"
           )

    create index(:theme_judgments, ["event_id"])

    create index(:theme_judgments, ["actor_id"])

    create index(:theme_judgments, ["theme_id"])

    create index(:theme_judgments, ["post_id"])
  end

  def down do
    drop_if_exists index(:theme_judgments, ["post_id"], name: "theme_judgments_post_id_index")

    drop_if_exists index(:theme_judgments, ["theme_id"], name: "theme_judgments_theme_id_index")

    drop_if_exists index(:theme_judgments, ["actor_id"], name: "theme_judgments_actor_id_index")

    drop_if_exists index(:theme_judgments, ["event_id"], name: "theme_judgments_event_id_index")

    drop_if_exists index(:theme_judgments, ["post_id", "theme_id"],
                     name: "theme_judgments_current_slot_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `theme_judgments` table without the `theme_judgments_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `theme_judgments` table without the `theme_judgments_post_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `theme_judgments` table without the `theme_judgments_theme_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `theme_judgments` table without the `theme_judgments_actor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `theme_judgments` table without the `theme_judgments_superseded_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:theme_judgments)

    drop_if_exists index(:theme_none_judgments, ["actor_id"],
                     name: "theme_none_judgments_actor_id_index"
                   )

    drop_if_exists index(:theme_none_judgments, ["event_id"],
                     name: "theme_none_judgments_event_id_index"
                   )

    drop_if_exists index(:theme_none_judgments, ["post_id"],
                     name: "theme_none_judgments_current_post_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `theme_none_judgments` table without the `theme_none_judgments_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `theme_none_judgments` table without the `theme_none_judgments_post_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `theme_none_judgments` table without the `theme_none_judgments_actor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `theme_none_judgments` table without the `theme_none_judgments_superseded_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:theme_none_judgments)
  end
end
