defmodule Wekui.Repo.Migrations.AddAuthorTagJudgments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:author_tag_none_judgments, primary_key: false) do
      add :superseded_by_id,
          references(:author_tag_none_judgments,
            column: :id,
            name: "author_tag_none_judgments_superseded_by_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :actor_id,
          references(:actors,
            column: :id,
            name: "author_tag_none_judgments_actor_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :author_id,
          references(:authors,
            column: :id,
            name: "author_tag_none_judgments_author_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "author_tag_none_judgments_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :superseded_at, :utc_datetime_usec
      add :judged_at, :utc_datetime_usec, null: false
      add :confidence, :float
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:author_tag_none_judgments, ["author_id"],
             name: "author_tag_none_judgments_current_author_index",
             unique: true,
             where: "superseded_at IS NULL"
           )

    create index(:author_tag_none_judgments, ["event_id"])

    create index(:author_tag_none_judgments, ["actor_id"])

    create table(:author_tag_judgments, primary_key: false) do
      add :superseded_by_id,
          references(:author_tag_judgments,
            column: :id,
            name: "author_tag_judgments_superseded_by_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :actor_id,
          references(:actors,
            column: :id,
            name: "author_tag_judgments_actor_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :tag_id,
          references(:author_tags,
            column: :id,
            name: "author_tag_judgments_tag_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :author_id,
          references(:authors,
            column: :id,
            name: "author_tag_judgments_author_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "author_tag_judgments_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :superseded_at, :utc_datetime_usec
      add :judged_at, :utc_datetime_usec, null: false
      add :confidence, :float
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:author_tag_judgments, ["author_id", "tag_id"],
             name: "author_tag_judgments_current_slot_index",
             unique: true,
             where: "superseded_at IS NULL"
           )

    create index(:author_tag_judgments, ["event_id"])

    create index(:author_tag_judgments, ["actor_id"])

    create index(:author_tag_judgments, ["tag_id"])

    create index(:author_tag_judgments, ["author_id"])
  end

  def down do
    drop_if_exists index(:author_tag_judgments, ["author_id"],
                     name: "author_tag_judgments_author_id_index"
                   )

    drop_if_exists index(:author_tag_judgments, ["tag_id"],
                     name: "author_tag_judgments_tag_id_index"
                   )

    drop_if_exists index(:author_tag_judgments, ["actor_id"],
                     name: "author_tag_judgments_actor_id_index"
                   )

    drop_if_exists index(:author_tag_judgments, ["event_id"],
                     name: "author_tag_judgments_event_id_index"
                   )

    drop_if_exists index(:author_tag_judgments, ["author_id", "tag_id"],
                     name: "author_tag_judgments_current_slot_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tag_judgments` table without the `author_tag_judgments_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tag_judgments` table without the `author_tag_judgments_author_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tag_judgments` table without the `author_tag_judgments_tag_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tag_judgments` table without the `author_tag_judgments_actor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tag_judgments` table without the `author_tag_judgments_superseded_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:author_tag_judgments)

    drop_if_exists index(:author_tag_none_judgments, ["actor_id"],
                     name: "author_tag_none_judgments_actor_id_index"
                   )

    drop_if_exists index(:author_tag_none_judgments, ["event_id"],
                     name: "author_tag_none_judgments_event_id_index"
                   )

    drop_if_exists index(:author_tag_none_judgments, ["author_id"],
                     name: "author_tag_none_judgments_current_author_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tag_none_judgments` table without the `author_tag_none_judgments_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tag_none_judgments` table without the `author_tag_none_judgments_author_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tag_none_judgments` table without the `author_tag_none_judgments_actor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tag_none_judgments` table without the `author_tag_none_judgments_superseded_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:author_tag_none_judgments)
  end
end
