defmodule Wekui.Repo.Migrations.AddNarrativeClaim do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:claims, primary_key: false) do
      add :superseded_by_id,
          references(:claims,
            column: :id,
            name: "claims_superseded_by_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :actor_id,
          references(:actors,
            column: :id,
            name: "claims_actor_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :place_id,
          references(:places,
            column: :id,
            name: "claims_place_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :event_id,
          references(:events,
            column: :id,
            name: "claims_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :superseded_at, :utc_datetime_usec
      add :confidence, :float
      add :first_seen_at, :utc_datetime_usec, null: false
      add :nuance, :text
      add :status, :text
      add :magnitude, :map
      add :subject, :text
      add :kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:claims, ["event_id", "superseded_at"])

    create index(:claims, ["actor_id"])

    create index(:claims, ["place_id"])

    create table(:claim_citations, primary_key: false) do
      add :post_id,
          references(:posts,
            column: :id,
            name: "claim_citations_post_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :claim_id,
          references(:claims,
            column: :id,
            name: "claim_citations_claim_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:claim_citations, ["post_id"])

    create unique_index(:claim_citations, [:claim_id, :post_id],
             name: "claim_citations_unique_post_per_claim_index"
           )
  end

  def down do
    drop_if_exists unique_index(:claim_citations, [:claim_id, :post_id],
                     name: "claim_citations_unique_post_per_claim_index"
                   )

    drop_if_exists index(:claim_citations, ["post_id"], name: "claim_citations_post_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `claim_citations` table without the `claim_citations_claim_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `claim_citations` table without the `claim_citations_post_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:claim_citations)

    drop_if_exists index(:claims, ["place_id"], name: "claims_place_id_index")

    drop_if_exists index(:claims, ["actor_id"], name: "claims_actor_id_index")

    drop_if_exists index(:claims, ["event_id", "superseded_at"],
                     name: "claims_event_id_superseded_at_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `claims` table without the `claims_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `claims` table without the `claims_place_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `claims` table without the `claims_actor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `claims` table without the `claims_superseded_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:claims)
  end
end
