defmodule Wekui.Repo.Migrations.ThemeCarriesItsRule do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:themes) do
      add :definition, :text
      add :applies_when, :text, null: false
      add :nature, :text, null: false
    end
  end

  def down do
    alter table(:themes) do
      remove :nature
      remove :applies_when
      remove :definition
    end
  end
end
