defmodule Wekui.Repo.Migrations.AddProposedBy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:themes) do
      add :proposed_by_actor_id,
          references(:actors,
            column: :id,
            name: "themes_proposed_by_actor_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :proposed_from_post_id,
          references(:posts,
            column: :id,
            name: "themes_proposed_from_post_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )
    end

    create index(:themes, ["proposed_from_post_id"])

    create index(:themes, ["proposed_by_actor_id"])

    alter table(:places) do
      add :proposed_by_actor_id,
          references(:actors,
            column: :id,
            name: "places_proposed_by_actor_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :proposed_from_post_id,
          references(:posts,
            column: :id,
            name: "places_proposed_from_post_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )
    end

    create index(:places, ["proposed_from_post_id"])

    create index(:places, ["proposed_by_actor_id"])

    alter table(:author_tags) do
      add :proposed_by_actor_id,
          references(:actors,
            column: :id,
            name: "author_tags_proposed_by_actor_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :proposed_from_post_id,
          references(:posts,
            column: :id,
            name: "author_tags_proposed_from_post_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )
    end

    create index(:author_tags, ["proposed_from_post_id"])

    create index(:author_tags, ["proposed_by_actor_id"])
  end

  def down do
    drop_if_exists index(:author_tags, ["proposed_by_actor_id"],
                     name: "author_tags_proposed_by_actor_id_index"
                   )

    drop_if_exists index(:author_tags, ["proposed_from_post_id"],
                     name: "author_tags_proposed_from_post_id_index"
                   )

    alter table(:author_tags) do
      remove :proposed_from_post_id
      remove :proposed_by_actor_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tags` table without the `author_tags_proposed_by_actor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tags` table without the `author_tags_proposed_from_post_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop_if_exists index(:places, ["proposed_by_actor_id"],
                     name: "places_proposed_by_actor_id_index"
                   )

    drop_if_exists index(:places, ["proposed_from_post_id"],
                     name: "places_proposed_from_post_id_index"
                   )

    alter table(:places) do
      remove :proposed_from_post_id
      remove :proposed_by_actor_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `places` table without the `places_proposed_by_actor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `places` table without the `places_proposed_from_post_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop_if_exists index(:themes, ["proposed_by_actor_id"],
                     name: "themes_proposed_by_actor_id_index"
                   )

    drop_if_exists index(:themes, ["proposed_from_post_id"],
                     name: "themes_proposed_from_post_id_index"
                   )

    alter table(:themes) do
      remove :proposed_from_post_id
      remove :proposed_by_actor_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `themes` table without the `themes_proposed_by_actor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `themes` table without the `themes_proposed_from_post_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
