defmodule Wekui.Repo.Migrations.AddTaxonomy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:themes, primary_key: false) do
      add :lifecycle, :text, null: false

      add :replaced_by_id,
          references(:themes,
            column: :id,
            name: "themes_replaced_by_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :parent_id,
          references(:themes,
            column: :id,
            name: "themes_parent_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :event_id,
          references(:events,
            column: :id,
            name: "themes_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :status_note, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:themes, ["replaced_by_id"])

    create index(:themes, ["parent_id"])

    create index(:themes, ["event_id"])

    create table(:author_tags, primary_key: false) do
      add :lifecycle, :text, null: false

      add :replaced_by_id,
          references(:author_tags,
            column: :id,
            name: "author_tags_replaced_by_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :event_id,
          references(:events,
            column: :id,
            name: "author_tags_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :status_note, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:author_tags, ["replaced_by_id"])

    create index(:author_tags, ["event_id"])
  end

  def down do
    drop_if_exists index(:author_tags, ["event_id"], name: "author_tags_event_id_index")

    drop_if_exists index(:author_tags, ["replaced_by_id"],
                     name: "author_tags_replaced_by_id_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tags` table without the `author_tags_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `author_tags` table without the `author_tags_replaced_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:author_tags)

    drop_if_exists index(:themes, ["event_id"], name: "themes_event_id_index")

    drop_if_exists index(:themes, ["parent_id"], name: "themes_parent_id_index")

    drop_if_exists index(:themes, ["replaced_by_id"], name: "themes_replaced_by_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `themes` table without the `themes_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `themes` table without the `themes_parent_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `themes` table without the `themes_replaced_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:themes)
  end
end
