defmodule Wekui.Repo.Migrations.PersonActor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:actors) do
      add :name, :text
    end

    create unique_index(:actors, [:event_id, :name], name: "actors_unique_person_index")
  end

  def down do
    drop_if_exists unique_index(:actors, [:event_id, :name], name: "actors_unique_person_index")

    alter table(:actors) do
      remove :name
    end
  end
end
