defmodule Wekui.Repo.Migrations.AddPerson do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:persons, primary_key: false) do
      add :event_id,
          references(:events,
            column: :id,
            name: "persons_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :status, :text, null: false
      add :kind, :text, null: false
      add :display_handle, :text
      add :normalized_name, :text, null: false
      add :full_name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:persons, ["normalized_name"])

    create unique_index(:persons, [:event_id, :normalized_name],
             name: "persons_unique_name_per_event_index"
           )
  end

  def down do
    drop_if_exists unique_index(:persons, [:event_id, :normalized_name],
                     name: "persons_unique_name_per_event_index"
                   )

    drop_if_exists index(:persons, ["normalized_name"], name: "persons_normalized_name_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `persons` table without the `persons_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:persons)
  end
end
