defmodule Wekui.Repo.Migrations.AddPlacement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:placements, primary_key: false) do
      add :superseded_by_id,
          references(:placements,
            column: :id,
            name: "placements_superseded_by_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :actor_id,
          references(:actors,
            column: :id,
            name: "placements_actor_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :place_id,
          references(:places,
            column: :id,
            name: "placements_place_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "placements_post_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "placements_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :superseded_at, :utc_datetime_usec
      add :judged_at, :utc_datetime_usec, null: false
      add :confidence, :float
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:placements, ["post_id"],
             name: "placements_current_post_index",
             unique: true,
             where: "superseded_at IS NULL"
           )

    create index(:placements, ["event_id"])

    create index(:placements, ["actor_id"])

    create index(:placements, ["place_id"])

    create table(:no_place_judgments, primary_key: false) do
      add :superseded_by_id,
          references(:no_place_judgments,
            column: :id,
            name: "no_place_judgments_superseded_by_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :actor_id,
          references(:actors,
            column: :id,
            name: "no_place_judgments_actor_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "no_place_judgments_post_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "no_place_judgments_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :superseded_at, :utc_datetime_usec
      add :judged_at, :utc_datetime_usec, null: false
      add :confidence, :float
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:no_place_judgments, ["post_id"],
             name: "no_place_judgments_current_post_index",
             unique: true,
             where: "superseded_at IS NULL"
           )

    create index(:no_place_judgments, ["event_id"])

    create index(:no_place_judgments, ["actor_id"])
  end

  def down do
    drop_if_exists index(:no_place_judgments, ["actor_id"],
                     name: "no_place_judgments_actor_id_index"
                   )

    drop_if_exists index(:no_place_judgments, ["event_id"],
                     name: "no_place_judgments_event_id_index"
                   )

    drop_if_exists index(:no_place_judgments, ["post_id"],
                     name: "no_place_judgments_current_post_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `no_place_judgments` table without the `no_place_judgments_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `no_place_judgments` table without the `no_place_judgments_post_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `no_place_judgments` table without the `no_place_judgments_actor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `no_place_judgments` table without the `no_place_judgments_superseded_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:no_place_judgments)

    drop_if_exists index(:placements, ["place_id"], name: "placements_place_id_index")

    drop_if_exists index(:placements, ["actor_id"], name: "placements_actor_id_index")

    drop_if_exists index(:placements, ["event_id"], name: "placements_event_id_index")

    drop_if_exists index(:placements, ["post_id"], name: "placements_current_post_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `placements` table without the `placements_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `placements` table without the `placements_post_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `placements` table without the `placements_place_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `placements` table without the `placements_actor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `placements` table without the `placements_superseded_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:placements)
  end
end
