defmodule Wekui.Repo.Migrations.AddClaimPlace do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:claims, ["place_id"], name: "claims_place_id_index")

    # alter table(:claims) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :place_id
    # end
    # 
    create table(:claim_places, primary_key: false) do
      add :place_id,
          references(:places,
            column: :id,
            name: "claim_places_place_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :claim_id,
          references(:claims,
            column: :id,
            name: "claim_places_claim_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :confidence, :float
      add :how_resolved, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:claim_places, ["place_id"])

    create unique_index(:claim_places, [:claim_id, :place_id],
             name: "claim_places_unique_place_per_claim_index"
           )
  end

  def down do
    drop_if_exists unique_index(:claim_places, [:claim_id, :place_id],
                     name: "claim_places_unique_place_per_claim_index"
                   )

    drop_if_exists index(:claim_places, ["place_id"], name: "claim_places_place_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `claim_places` table without the `claim_places_claim_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `claim_places` table without the `claim_places_place_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:claim_places)

    # alter table(:claims) do
    # This is the `down` migration of the statement:
    #
    #     remove :place_id
    #
    # 
    # add :place_id, references(:places, column: :id, name: "claims_place_id_fkey", type: :uuid, on_delete: :restrict)
    # end
    # 
    create index(:claims, ["place_id"])
  end
end
