defmodule Wekui.Repo.Migrations.UnplacedPlace do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :unplaced_place_id,
          references(:places, column: :id, name: "events_unplaced_place_id_fkey", type: :uuid)
    end
  end

  def down do
    alter table(:events) do
      remove :unplaced_place_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `events` table without the `events_unplaced_place_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
