defmodule Wekui.Repo.Migrations.AddClaimSupport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:claims) do
      add :support, :text, null: false, default: "unverified"
      add :support_note, :text
    end
  end

  def down do
    alter table(:claims) do
      remove :support_note
      remove :support
    end
  end
end
