defmodule Wekui.Repo.Migrations.AddPersonMerge do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:persons) do
      add :merged_at, :utc_datetime_usec
      add :merge_note, :text

      add :merged_into_id,
          references(:persons,
            column: :id,
            name: "persons_merged_into_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )
    end
  end

  def down do
    alter table(:persons) do
      remove :merged_into_id
      remove :merge_note
      remove :merged_at
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `persons` table without the `persons_merged_into_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
