defmodule Wekui.Repo.Migrations.ActCanTargetATheme do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:curation_acts) do
      add :theme_id,
          references(:themes,
            column: :id,
            name: "curation_acts_theme_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )
    end
  end

  def down do
    alter table(:curation_acts) do
      remove :theme_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `curation_acts` table without the `curation_acts_theme_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
