defmodule Wekui.Repo.Migrations.Actor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:actors, primary_key: false) do
      add :event_id,
          references(:events,
            column: :id,
            name: "actors_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :content_hash, :text
      add :prompt, :text
      add :model, :text
      add :kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:actors, [:event_id, :content_hash, :model],
             name: "actors_unique_agent_index"
           )
  end

  def down do
    drop_if_exists unique_index(:actors, [:event_id, :content_hash, :model],
                     name: "actors_unique_agent_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `actors` table without the `actors_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:actors)
  end
end
