defmodule Wekui.Repo.Migrations.CreateAcquisition do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:searches, primary_key: false) do
      add :status, :text, null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "searches_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :status_note, :text
      add :result_mode, :text, null: false
      add :slice_seconds, :bigint, null: false
      add :window_end, :utc_datetime_usec
      add :window_start, :utc_datetime_usec, null: false
      add :intent, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:searches, ["event_id"])

    create unique_index(:searches, [:event_id, :name],
             name: "searches_unique_name_per_event_index"
           )

    create table(:search_terms, primary_key: false) do
      add :search_id,
          references(:searches,
            column: :id,
            name: "search_terms_search_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :lang, :text, null: false
      add :term, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:search_terms, ["search_id"])

    create table(:search_places, primary_key: false) do
      add :place_id,
          references(:places,
            column: :id,
            name: "search_places_place_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :search_id,
          references(:searches,
            column: :id,
            name: "search_places_search_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:search_places, ["place_id"])

    create unique_index(:search_places, [:search_id, :place_id],
             name: "search_places_unique_place_per_search_index"
           )

    create table(:query_terms, primary_key: false) do
      add :search_term_id,
          references(:search_terms,
            column: :id,
            name: "query_terms_search_term_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :query_id,
          references(:queries,
            column: :id,
            name: "query_terms_query_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:query_names, primary_key: false) do
      add :place_name_id,
          references(:place_names,
            column: :id,
            name: "query_names_place_name_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :query_id,
          references(:queries,
            column: :id,
            name: "query_names_query_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:queries, primary_key: false) do
      add :place_id,
          references(:places,
            column: :id,
            name: "queries_place_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :search_id,
          references(:searches,
            column: :id,
            name: "queries_search_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :posts_new, :bigint
      add :posts_found, :bigint
      add :discarded_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :status_note, :text
      add :intent, :text
      add :slice_end, :utc_datetime_usec, null: false
      add :slice_start, :utc_datetime_usec, null: false
      add :query_text, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:query_terms, ["search_term_id"])

    create unique_index(:query_terms, [:query_id, :search_term_id],
             name: "query_terms_unique_term_per_query_index"
           )

    create index(:query_names, ["place_name_id"])

    create unique_index(:query_names, [:query_id, :place_name_id],
             name: "query_names_unique_name_per_query_index"
           )

    create index(:queries, ["place_id"])

    create index(:queries, ["search_id"])

    create unique_index(:queries, [:search_id, :query_text],
             name: "queries_unique_text_per_search_index"
           )
  end

  def down do
    drop_if_exists unique_index(:queries, [:search_id, :query_text],
                     name: "queries_unique_text_per_search_index"
                   )

    drop_if_exists index(:queries, ["search_id"], name: "queries_search_id_index")

    drop_if_exists index(:queries, ["place_id"], name: "queries_place_id_index")

    drop_if_exists unique_index(:query_names, [:query_id, :place_name_id],
                     name: "query_names_unique_name_per_query_index"
                   )

    drop_if_exists index(:query_names, ["place_name_id"], name: "query_names_place_name_id_index")

    drop_if_exists unique_index(:query_terms, [:query_id, :search_term_id],
                     name: "query_terms_unique_term_per_query_index"
                   )

    drop_if_exists index(:query_terms, ["search_term_id"],
                     name: "query_terms_search_term_id_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `queries` table without the `queries_search_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `queries` table without the `queries_place_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:queries)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `query_names` table without the `query_names_query_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `query_names` table without the `query_names_place_name_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:query_names)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `query_terms` table without the `query_terms_query_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `query_terms` table without the `query_terms_search_term_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:query_terms)

    drop_if_exists unique_index(:search_places, [:search_id, :place_id],
                     name: "search_places_unique_place_per_search_index"
                   )

    drop_if_exists index(:search_places, ["place_id"], name: "search_places_place_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `search_places` table without the `search_places_search_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `search_places` table without the `search_places_place_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:search_places)

    drop_if_exists index(:search_terms, ["search_id"], name: "search_terms_search_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `search_terms` table without the `search_terms_search_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:search_terms)

    drop_if_exists unique_index(:searches, [:event_id, :name],
                     name: "searches_unique_name_per_event_index"
                   )

    drop_if_exists index(:searches, ["event_id"], name: "searches_event_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `searches` table without the `searches_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:searches)
  end
end
