defmodule Wekui.Repo.Migrations.AddPipelineRun do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:runs, primary_key: false) do
      add :actor_id,
          references(:actors,
            column: :id,
            name: "runs_actor_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "runs_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :finished_at, :utc_datetime_usec
      add :summary, :map
      add :options, :map
      add :status, :text, null: false
      add :kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:runs, ["actor_id"])

    create index(:runs, ["event_id", "inserted_at"])
  end

  def down do
    drop_if_exists index(:runs, ["event_id", "inserted_at"],
                     name: "runs_event_id_inserted_at_index"
                   )

    drop_if_exists index(:runs, ["actor_id"], name: "runs_actor_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `runs` table without the `runs_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `runs` table without the `runs_actor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:runs)
  end
end
