defmodule Wekui.Repo.Migrations.CreateCapture do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add :author_id,
          references(:authors,
            column: :id,
            name: "posts_author_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "posts_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :payload, :map, null: false
      add :posted_at, :utc_datetime_usec, null: false
      add :text, :text, null: false
      add :x_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:authors, primary_key: false) do
      add :event_id,
          references(:events,
            column: :id,
            name: "authors_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :display_name, :text
      add :handle, :text, null: false
      add :x_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:posts, ["author_id"])

    create unique_index(:posts, [:event_id, :x_id], name: "posts_unique_x_id_per_event_index")

    create unique_index(:authors, [:event_id, :x_id], name: "authors_unique_x_id_per_event_index")

    create table(:appearances, primary_key: false) do
      add :query_id,
          references(:queries,
            column: :id,
            name: "appearances_query_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "appearances_post_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:appearances, ["query_id"])

    create unique_index(:appearances, [:post_id, :query_id],
             name: "appearances_unique_post_per_query_index"
           )
  end

  def down do
    drop_if_exists unique_index(:appearances, [:post_id, :query_id],
                     name: "appearances_unique_post_per_query_index"
                   )

    drop_if_exists index(:appearances, ["query_id"], name: "appearances_query_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `appearances` table without the `appearances_post_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `appearances` table without the `appearances_query_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:appearances)

    drop_if_exists unique_index(:authors, [:event_id, :x_id],
                     name: "authors_unique_x_id_per_event_index"
                   )

    drop_if_exists unique_index(:posts, [:event_id, :x_id],
                     name: "posts_unique_x_id_per_event_index"
                   )

    drop_if_exists index(:posts, ["author_id"], name: "posts_author_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `authors` table without the `authors_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:authors)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `posts` table without the `posts_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `posts` table without the `posts_author_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:posts)
  end
end
