defmodule Wekui.Repo.Migrations.CreateGazetteer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:places, primary_key: false) do
      add :lifecycle, :text, null: false

      add :replaced_by_id,
          references(:places,
            column: :id,
            name: "places_replaced_by_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :parent_id,
          references(:places,
            column: :id,
            name: "places_parent_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :event_id,
          references(:events,
            column: :id,
            name: "places_event_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :status_note, :text
      add :canonical_name, :text, null: false
      add :type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:places, ["replaced_by_id"])

    create index(:places, ["parent_id"])

    create index(:places, ["event_id"])

    create table(:place_names, primary_key: false) do
      add :place_id,
          references(:places,
            column: :id,
            name: "place_names_place_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :emission, :text, null: false
      add :kind, :text, null: false
      add :normalized, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:place_names, ["normalized"])

    create index(:place_names, ["place_id"])
  end

  def down do
    drop_if_exists index(:place_names, ["place_id"], name: "place_names_place_id_index")

    drop_if_exists index(:place_names, ["normalized"], name: "place_names_normalized_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `place_names` table without the `place_names_place_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:place_names)

    drop_if_exists index(:places, ["event_id"], name: "places_event_id_index")

    drop_if_exists index(:places, ["parent_id"], name: "places_parent_id_index")

    drop_if_exists index(:places, ["replaced_by_id"], name: "places_replaced_by_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `places` table without the `places_event_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `places` table without the `places_parent_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `places` table without the `places_replaced_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:places)
  end
end
