defmodule Wekui.Repo.Migrations.AddClaimPersonAndPlaceMention do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:claims) do
      add :place_mention, :text
    end

    create table(:claim_persons, primary_key: false) do
      add :person_id,
          references(:persons,
            column: :id,
            name: "claim_persons_person_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :claim_id,
          references(:claims,
            column: :id,
            name: "claim_persons_claim_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:claim_persons, ["person_id"])

    create unique_index(:claim_persons, [:claim_id, :person_id],
             name: "claim_persons_unique_person_per_claim_index"
           )
  end

  def down do
    drop_if_exists unique_index(:claim_persons, [:claim_id, :person_id],
                     name: "claim_persons_unique_person_per_claim_index"
                   )

    drop_if_exists index(:claim_persons, ["person_id"], name: "claim_persons_person_id_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `claim_persons` table without the `claim_persons_claim_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `claim_persons` table without the `claim_persons_person_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:claim_persons)

    alter table(:claims) do
      remove :place_mention
    end
  end
end
